### ISSUE TITLE
Requesting to change folder names to get readability

### ISSUE THREAD

**Issue by jonyahmed19** [mrhm-dev/full-stack-army#38]
Hey,
We can modify folder names for a bit more readability.
For Example:
**demo** to **demos**
**live-classes** to **live-classes-links**
**projects** to **class-projects**
so on.

It is my personal opinion.
What do you think?
Thanks

**Comment by adityackr** [comment]
@jonyahmed19 Thank you for your suggestions. But, we cannot change folder names, because already every folders you mentioned are linked in our all markdown files. If we change the folder name we have change every file, which is time consuming task. That is why we cannot change the directory names as you proposed.

**Comment by adityackr** [comment]
@jonyahmed19 Please see the main README file. I think now it is understandable.
